# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoDlg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(370, 363)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushBtnCancle = QtWidgets.QPushButton(Dialog)
        self.pushBtnCancle.setGeometry(QtCore.QRect(140, 310, 75, 25))
        self.pushBtnCancle.setObjectName("pushBtnCancle")
        self.pushBtnOkay = QtWidgets.QPushButton(Dialog)
        self.pushBtnOkay.setGeometry(QtCore.QRect(230, 310, 75, 25))
        self.pushBtnOkay.setObjectName("pushBtnOkay")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 31, 251, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelNo = QtWidgets.QLabel(self.layoutWidget)
        self.labelNo.setObjectName("labelNo")
        self.horizontalLayout.addWidget(self.labelNo)
        self.lineEdNo = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdNo.setObjectName("lineEdNo")
        self.horizontalLayout.addWidget(self.lineEdNo)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 71, 251, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.layoutWidget1)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.lineEdName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdName.setObjectName("lineEdName")
        self.horizontalLayout_2.addWidget(self.lineEdName)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 111, 251, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelAge = QtWidgets.QLabel(self.layoutWidget2)
        self.labelAge.setObjectName("labelAge")
        self.horizontalLayout_3.addWidget(self.labelAge)
        self.lineEdAge = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdAge.setObjectName("lineEdAge")
        self.horizontalLayout_3.addWidget(self.lineEdAge)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 190, 251, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelPhone = QtWidgets.QLabel(self.layoutWidget3)
        self.labelPhone.setObjectName("labelPhone")
        self.horizontalLayout_5.addWidget(self.labelPhone)
        self.lineEdPhone = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdPhone.setObjectName("lineEdPhone")
        self.horizontalLayout_5.addWidget(self.lineEdPhone)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(59, 230, 251, 73))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelOtherInfo = QtWidgets.QLabel(self.layoutWidget4)
        self.labelOtherInfo.setObjectName("labelOtherInfo")
        self.horizontalLayout_6.addWidget(self.labelOtherInfo)
        self.textEdOtherinfo = QtWidgets.QTextEdit(self.layoutWidget4)
        self.textEdOtherinfo.setObjectName("textEdOtherinfo")
        self.horizontalLayout_6.addWidget(self.textEdOtherinfo)
        self.layoutWidget5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(61, 151, 251, 22))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelGender = QtWidgets.QLabel(self.layoutWidget5)
        self.labelGender.setEnabled(True)
        self.labelGender.setMinimumSize(QtCore.QSize(20, 20))
        self.labelGender.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelGender.setObjectName("labelGender")
        self.horizontalLayout_4.addWidget(self.labelGender)
        self.comboBoxAge = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBoxAge.setEnabled(True)
        self.comboBoxAge.setMinimumSize(QtCore.QSize(210, 0))
        self.comboBoxAge.setObjectName("comboBoxAge")
        self.horizontalLayout_4.addWidget(self.comboBoxAge)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "联系人信息"))
        self.pushBtnCancle.setText(_translate("Dialog", "取消"))
        self.pushBtnOkay.setText(_translate("Dialog", "保存"))
        self.labelNo.setText(_translate("Dialog", "序号:"))
        self.labelName.setText(_translate("Dialog", "姓名:"))
        self.labelAge.setText(_translate("Dialog", "年龄:"))
        self.labelPhone.setText(_translate("Dialog", "电话:"))
        self.labelOtherInfo.setText(_translate("Dialog", "备注:"))
        self.labelGender.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGender.setText(_translate("Dialog", "性别:"))
        self.comboBoxAge.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))

